name: Winkor
targets:
  Winkor:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [WinkorApp]
    settings:
      base:
        PRODUCT_NAME: Winkor
        EXECUTABLE_NAME: Winkor
        INFOPLIST_PATH: WinkorApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.winkor.emulator
        SWIFT_VERSION: 5.0
        CODE_SIGNING_ALLOWED: NO
        METAL_ENABLE_DEBUG_INFO: NO
        ENABLE_BITCODE: NO
        OTHER_LDFLAGS: "-lstdc++"
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        GCC_OPTIMIZATION_LEVEL: s
