name: Winkor
options:
  bundleIdPrefix: com.devz906
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"

settings:
  DEVELOPMENT_TEAM: YOUR_TEAM_ID
  CODE_SIGN_STYLE: Automatic
  PRODUCT_BUNDLE_IDENTIFIER: com.devz906.winkor
  MARKETING_VERSION: 1.0
  CURRENT_PROJECT_VERSION: 1

targets:
  Winkor:
    type: application
    platform: iOS
    sources:
      - path: WinkorApp
        includes:
          - "**/*.swift"
    resources:
      - path: WinkorApp/Resources
    settings:
      INFOPLIST_FILE: WinkorApp/Info.plist
      PRODUCT_NAME: Winkor
      SUPPORTED_PLATFORMS: iphoneos
      SUPPORTED_DEVICE_FAMILIES: [1, 2]  # iPhone and iPad
      ENABLE_BITCODE: NO
      STRIP_INSTALLED_PRODUCT: NO
      DEAD_CODE_STRIPPING: NO
      ONLY_ACTIVE_ARCH: NO

schemes:
  Winkor:
    build:
      targets:
        Winkor: all
    run:
      config: Debug
    archive:
      config: Release
